import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import Header from "./__components/Header";
import "./globals.css";

const mulish = Mulish({ subsets: ["latin"], weight: ["500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
